//! Schema → Rust type generator for the BeerJSON 2.x schemas.
//!
//! The schemas live in the `vendor/beerjson/` git submodule (pinning
//! the upstream `beerjson/beerjson` repo, or a fork branch until
//! pending PRs land). Run from the repo root:
//!
//! ```sh
//! cargo run --manifest-path crates/werb-beerjson/tools/Cargo.toml \
//!   -- vendor/beerjson/json/ crates/werb-beerjson/src/generated.rs
//! ```
//!
//! `pnpm gen:beerjson` wraps that command. The output is committed to
//! the repo so day-to-day builds need no codegen step.
//!
//! Depends on the patched `barbacane-dev/typify` fork — the upstream
//! `oxidecomputer/typify` doesn't yet bundle transitive internal `$ref`
//! values from external schemas (which BeerJSON depends on heavily).

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;
use typify::{TypeSpace, TypeSpaceSettings};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = std::env::args().skip(1);
    let schemas_dir = PathBuf::from(
        args.next()
            .expect("usage: gen <schemas-dir> <output-file>"),
    );
    let output_path = PathBuf::from(args.next().expect("usage: gen <schemas-dir> <output-file>"));

    let mut externals: BTreeMap<String, serde_json::Value> = BTreeMap::new();
    let mut root: Option<serde_json::Value> = None;

    for entry in fs::read_dir(&schemas_dir)? {
        let entry = entry?;
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if !name.ends_with(".json") {
            continue;
        }
        let content = fs::read_to_string(&path)?;
        let value: serde_json::Value = serde_json::from_str(&content)?;
        if name == "beer.json" {
            root = Some(value);
        } else {
            externals.insert(name.to_string(), value);
        }
    }

    let root = root.expect("beer.json not found in schemas dir");

    let mut ts = TypeSpace::new(
        TypeSpaceSettings::default()
            .with_derive("PartialEq".to_string())
            .with_struct_builder(false),
    );
    ts.add_schema_with_externals(root, externals)?;

    let intro = "// AUTO-GENERATED by crates/werb-beerjson/tools/gen.rs from\n\
                 // vendor/beerjson/json/*.json. Do not edit by hand. Run\n\
                 // `pnpm gen:beerjson` to regenerate after a schema bump.\n\
                 #![allow(clippy::redundant_closure_call)]\n\
                 #![allow(clippy::needless_lifetimes)]\n\
                 #![allow(clippy::match_single_binding)]\n\
                 #![allow(clippy::clone_on_copy)]\n\
                 #![allow(clippy::too_many_arguments)]\n\
                 #![allow(clippy::derivable_impls)]\n\
                 #![allow(clippy::large_enum_variant)]\n\
                 #![allow(dead_code)]\n";
    let body = ts.to_stream().to_string();
    let unformatted = format!("{intro}\n{body}");

    let formatted = rustfmt_wrapper::rustfmt(&unformatted).unwrap_or(unformatted);
    fs::write(&output_path, formatted)?;
    eprintln!("wrote {}", output_path.display());
    Ok(())
}
